"""Lobby — joined-but-not-yet-seated player names.

Owned by the engine so a game reset can survive across the chair
store's restore (the same way ``ChairStore`` and ``CharacterPool`` do).

The lobby exists so players can join the game from their own phones
*before* the Storyteller has finalised the seating: the player loads
``/player`` on the LAN, types their name, and posts to
``/api/lobby/join``. Their entry sits in the lobby until the
Storyteller drags it onto a chair on the Local UI, which calls
``/api/lobby/assign`` and stamps the chair's name.

Each entry is a dict::

    {"id": str,                     # opaque token (set as a cookie)
     "name": str,
     "joined_at": float,            # epoch seconds
     "assigned_chair_id": int|None,
     "character_revealed": bool}    # storyteller has pushed the
                                    # player's assigned character to
                                    # their phone — clears when the
                                    # player taps "Hide"

Lobby ids are short hex tokens generated by :func:`secrets.token_hex`,
not sequential ints — they double as the player's session cookie so
the Player UI can come back to its own record across reloads.
"""

from __future__ import annotations

import secrets
import threading
import time
from typing import Any, Dict, List, Optional


class Lobby:
    """Holds the joined-players list for one engine instance.

    Thread-safe: read by HTTP request handlers and mutated both by the
    Storyteller-driven assign endpoints and by player join requests.
    """

    def __init__(self) -> None:
        self._entries: Dict[str, Dict[str, Any]] = {}
        self._lock = threading.Lock()

    # ------------------------------------------------------------------
    # Pickling support — ``threading.Lock`` isn't picklable.
    # ------------------------------------------------------------------

    def __getstate__(self) -> Dict[str, Any]:
        state = self.__dict__.copy()
        state.pop("_lock", None)
        return state

    def __setstate__(self, state: Dict[str, Any]) -> None:
        self.__dict__.update(state)
        self._lock = threading.Lock()

    # ------------------------------------------------------------------

    def list(self) -> List[Dict[str, Any]]:
        """Snapshot of every lobby entry, oldest-joined first."""
        with self._lock:
            return sorted(
                (dict(e) for e in self._entries.values()),
                key=lambda e: e["joined_at"],
            )

    def get(self, lobby_id: str) -> Optional[Dict[str, Any]]:
        with self._lock:
            entry = self._entries.get(lobby_id)
            return dict(entry) if entry is not None else None

    def join(self, name: str) -> Dict[str, Any]:
        """Record a new joined player. Returns the new entry.

        ``name`` is trimmed and capped at 64 characters. Raises
        ``ValueError`` if the name is empty, or if another lobby entry
        already holds that name (case-insensitive). Same-browser
        re-joins are handled one layer up by the ``/api/lobby/join``
        handler in ``ui.py``, which routes a request that carries a
        live ``botc_lobby_id`` cookie to :meth:`rename` instead — so
        this method only ever sees genuinely-new joins, and a name
        clash here means a *different* player is trying to take the
        same name.
        """
        clean = (name or "").strip()[:64]
        if not clean:
            raise ValueError("name is required")
        with self._lock:
            for entry in self._entries.values():
                if entry["name"].lower() == clean.lower():
                    raise ValueError(
                        f"name {clean!r} is already taken")
            lobby_id = secrets.token_hex(8)
            # token_hex collisions at 64 bits are vanishingly rare, but
            # be defensive: regenerate on the off chance.
            while lobby_id in self._entries:
                lobby_id = secrets.token_hex(8)
            entry = {
                "id": lobby_id,
                "name": clean,
                "joined_at": time.time(),
                "assigned_chair_id": None,
                "character_revealed": False,
            }
            self._entries[lobby_id] = entry
            return dict(entry)

    def rename(self, lobby_id: str, name: str) -> Optional[Dict[str, Any]]:
        """Update the display name of an existing lobby entry.

        Returns the updated entry, or ``None`` if no entry has that
        ``lobby_id`` (so a stale cookie from a previous session falls
        through to a fresh ``join`` at the call site). Raises
        ``ValueError`` if ``name`` is empty, or if a *different* lobby
        entry already holds that name (case-insensitive). Renaming an
        entry to its own current name (modulo case/whitespace) is a
        no-op and returns the entry unchanged.
        """
        clean = (name or "").strip()[:64]
        if not clean:
            raise ValueError("name is required")
        with self._lock:
            entry = self._entries.get(lobby_id)
            if entry is None:
                return None
            for other in self._entries.values():
                if (other["id"] != lobby_id
                        and other["name"].lower() == clean.lower()):
                    raise ValueError(
                        f"name {clean!r} is already taken")
            entry["name"] = clean
            return dict(entry)

    def assign(self, lobby_id: str, chair_id: int) -> Optional[Dict[str, Any]]:
        """Mark a lobby entry as seated at ``chair_id``.

        The caller is responsible for actually writing the chair's
        ``name`` field — :class:`Lobby` only tracks the assignment
        side. Returns the updated entry, or ``None`` if no such id.
        """
        with self._lock:
            entry = self._entries.get(lobby_id)
            if entry is None:
                return None
            # If another lobby entry was assigned to this chair, knock
            # it loose first so a chair has at most one occupant.
            for other in self._entries.values():
                if (other["id"] != lobby_id
                        and other["assigned_chair_id"] == chair_id):
                    other["assigned_chair_id"] = None
            entry["assigned_chair_id"] = int(chair_id)
            return dict(entry)

    def unassign(self, lobby_id: str) -> Optional[Dict[str, Any]]:
        with self._lock:
            entry = self._entries.get(lobby_id)
            if entry is None:
                return None
            entry["assigned_chair_id"] = None
            return dict(entry)

    def unassign_chair(self, chair_id: int) -> Optional[Dict[str, Any]]:
        """Drop whichever lobby entry is sitting at ``chair_id`` (if any)."""
        with self._lock:
            for entry in self._entries.values():
                if entry["assigned_chair_id"] == chair_id:
                    entry["assigned_chair_id"] = None
                    return dict(entry)
            return None

    def remove(self, lobby_id: str) -> Optional[Dict[str, Any]]:
        with self._lock:
            return self._entries.pop(lobby_id, None)

    def clear(self) -> None:
        with self._lock:
            self._entries.clear()

    def reveal_characters_to_seated(self) -> List[Dict[str, Any]]:
        """Mark every lobby entry that's seated at a chair as having
        had their character "revealed" to their phone. The Player UI
        polls its own entry and, while ``character_revealed`` is True,
        shows the assigned chair's character token. The player can hit
        Hide to clear their own entry; the storyteller can hit Reveal
        again to re-set the flag.

        Returns the list of entries that were flipped on.
        """
        flipped: List[Dict[str, Any]] = []
        with self._lock:
            for entry in self._entries.values():
                if entry.get("assigned_chair_id") is not None:
                    entry["character_revealed"] = True
                    flipped.append(dict(entry))
        return flipped

    def hide_character(self, lobby_id: str) -> Optional[Dict[str, Any]]:
        """Clear ``character_revealed`` for one lobby entry (the player
        tapped Hide on their phone). Idempotent."""
        with self._lock:
            entry = self._entries.get(lobby_id)
            if entry is None:
                return None
            entry["character_revealed"] = False
            return dict(entry)

    def clear_all_character_reveals(self) -> None:
        """Reset every lobby entry's ``character_revealed`` to False.
        Used on engine reset / new game."""
        with self._lock:
            for entry in self._entries.values():
                entry["character_revealed"] = False

    def find_for_chair(self, chair_id: int) -> Optional[Dict[str, Any]]:
        with self._lock:
            for entry in self._entries.values():
                if entry["assigned_chair_id"] == chair_id:
                    return dict(entry)
            return None
